!------------------------------------------------------------------
!  		INCLUDE FILE FOR ALEXI MODEL PARAMETERS
!------------------------------------------------------------------

!  PBL parameters
      parameter(mli=41)		! Number input PBL levels
      parameter(ml=8000)	! Number interpolated PBL levels
      parameter(mt=8000)	! Size of PBL lookup tables

!  ALEXI IERR codes
      parameter(BAD=-9999.0)
      parameter(SUCCESS=0)
